// 由 gallery/index.html 内嵌 CARDS 数据生成：卡 id → 中文名/分类（与画廊一致）
export const TPL_META: Record<string, { name: string; category: string }> = {
  "focus-dim-spotlight": { name: "聚焦压暗切换", category: "强调标注" },
  "hand-drawn-ellipse": { name: "手绘圈重点", category: "强调标注" },
  "highlighter-sweep": { name: "荧光笔高亮扫过", category: "强调标注" },
  "scribble-annotation": { name: "手绘圈注箭头", category: "强调标注" },
  "callout-line-label": { name: "标注引出线", category: "强调标注" },
  "converging-arrows": { name: "双箭头聚焦", category: "强调标注" },
  "corner-bracket-frame": { name: "对角角框", category: "强调标注" },
  "ink-underline": { name: "墨迹下划线", category: "强调标注" },
  "magnifier-detail": { name: "局部放大镜", category: "强调标注" },
  "quote-hold-arrow": { name: "金句停留", category: "强调标注" },
  "strike-and-replace": { name: "划线纠错替换", category: "强调标注" },
  "lower-third-nameplate": { name: "人名条展示牌", category: "人物互动" },
  "behind-text-title": { name: "人后大字视差", category: "人物互动" },
  "chevron-lower-third": { name: "动态人名条", category: "人物互动" },
  "danmu-bubble-praise": { name: "弹幕气泡", category: "人物互动" },
  "host-shrink-to-chip": { name: "人物缩位让台", category: "人物互动" },
  "subscribe-cta": { name: "多平台关注 CTA", category: "人物互动" },
  "x-follow-card": { name: "关注卡弹出", category: "人物互动" },
  "douyin-follow-card": { name: "抖音主页关注卡", category: "人物互动" },
  "bar-chart-growth": { name: "柱状增长", category: "数据信息图" },
  "chart-grow": { name: "图表生长", category: "数据信息图" },
  "line-chart-story-draw": { name: "折线分段推演", category: "数据信息图" },
  "metric-with-sparkline": { name: "数字带趋势", category: "数据信息图" },
  "number-counter": { name: "数字滚动计数", category: "数据信息图" },
  "number-slab-pop": { name: "数字弹出", category: "数据信息图" },
  "info-term-card": { name: "名词解释悬浮卡", category: "数据信息图" },
  "map-route-pin": { name: "地图路线图钉", category: "数据信息图" },
  "numbered-step-stack": { name: "编号步骤堆入", category: "数据信息图" },
  "step-timeline-vertical": { name: "竖向步骤线", category: "数据信息图" },
  "ui-prop-theater": { name: "界面道具剧场", category: "数据信息图" },
  "chat-message-flow": { name: "聊天记录自演", category: "素材呈现" },
  "cursor-actor-demo": { name: "光标演员演示", category: "素材呈现" },
  "evidence-scroll-tour": { name: "证据长页慢滚", category: "素材呈现" },
  "media-pop-in": { name: "素材弹入堆叠", category: "素材呈现" },
  "news-card-desk": { name: "新闻卡片划重点", category: "素材呈现" },
  "ui-flow-theater": { name: "界面流程剧场", category: "素材呈现" },
  "chat-gpt": { name: "ChatGPT 对话框", category: "素材呈现" },
  "claude-code": { name: "编码智能体终端", category: "素材呈现" },
  "glass-code-walk": { name: "玻璃代码走读", category: "素材呈现" },
  "gooey-morph": { name: "图块拼入", category: "素材呈现" },
  "logo-enter": { name: "Logo 登场", category: "素材呈现" },
  "motion-blur-slam-in": { name: "模糊甩入急停", category: "素材呈现" },
  "pencil-sketch-draw": { name: "铅笔手绘揭示", category: "素材呈现" },
  "terminal-typing-log": { name: "终端逐行推进", category: "素材呈现" },
  "slow-pull-reveal": { name: "缓拉全貌", category: "运镜" },
  "slow-push-in": { name: "缓推特写", category: "运镜" },
  "cursor-locked-zoom": { name: "光标锁定跟拍", category: "运镜" },
  "orbit-drift": { name: "环绕微漂", category: "运镜" },
  "pip-zoom-box": { name: "画中画放大", category: "运镜" },
  "stage-keyframe-tour": { name: "长页兴趣点巡游", category: "运镜" },
  "sway-parallax": { name: "左右摇移", category: "运镜" },
  "tilt-3d-page": { name: "3D 立面展示", category: "运镜" },
  "black-slam-transition": { name: "黑震切转场", category: "转场结构" },
  "chapter-title-card": { name: "章节标题卡", category: "转场结构" },
  "color-slam-beat-card": { name: "纯色硬切节拍卡", category: "转场结构" },
  "overexpose-flip-transition": { name: "过曝翻页转场", category: "转场结构" },
  "particle-weld-transition": { name: "粒子溶接转场", category: "转场结构" },
  "pullback-cool-transition": { name: "后拉冷却转场", category: "转场结构" },
  "push-through-transition": { name: "推穿转场", category: "转场结构" },
  "shape-wipe-transition": { name: "色块扫屏转场", category: "转场结构" },
  "whip-pan-transition": { name: "横甩转场", category: "转场结构" },
  "caret-wipe-transition": { name: "光标擦除转场", category: "转场结构" },
  "chapter-progress-list": { name: "章节进度", category: "转场结构" },
  "long-take-world": { name: "长镜头世界画布", category: "转场结构" },
  "impact-open-title": { name: "冲击开场", category: "字幕花字" },
  "keyword-pop-highlight": { name: "关键词弹出强调", category: "字幕花字" },
  "slab-punch-title": { name: "重点放大", category: "字幕花字" },
  "type-contrast-emphasis": { name: "字体对比重音", category: "字幕花字" },
  "alt-block-lines": { name: "双色块对句", category: "字幕花字" },
  "count-badge-title": { name: "数字重音标题", category: "字幕花字" },
  "line-by-line-slide": { name: "逐行滑入", category: "字幕花字" },
  "outline-box-title": { name: "描边框标题", category: "字幕花字" },
  "per-character-rise": { name: "逐字升起", category: "字幕花字" },
  "quote-bracket-pull": { name: "引号夹句", category: "字幕花字" },
  "quote-card": { name: "金句大字卡", category: "字幕花字" },
  "soft-blur-in": { name: "柔焦淡入", category: "字幕花字" },
  "speed-slab-title": { name: "速度块标题", category: "字幕花字" },
  "tracking-in": { name: "字距收拢", category: "字幕花字" },
  "typewriter-reveal": { name: "打字机档案戳", category: "字幕花字" },
};

/** 画廊分类顺序 */
export const TPL_CATEGORIES = ["强调标注", "人物互动", "数据信息图", "素材呈现", "运镜", "转场结构", "字幕花字"];
